name: ireagation_system
description: "Smart Agriculture Management System"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  intl: ^0.20.3
  http: ^1.6.0
  uuid: ^4.6.0
  supabase_flutter: ^2.17.2
  geolocator: ^14.0.3
  google_fonts: ^8.2.1
  shared_preferences: ^2.5.5
  fl_chart: ^1.2.0
  mqtt_client: ^10.11.11
  flutter_dotenv: ^6.0.1
  geocoding: ^5.0.0
  image_picker: ^1.2.3
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.jpg"
  min_sdk_android: 21
