import 'package:flutter/material.dart';

class LanguageProvider with ChangeNotifier {
  String _currentLanguage = 'English';

  final List<String> supportedLanguages = [
    'English',
    'Hindi',
    'Telugu',
    'Tamil',
    'Marathi',
    'Spanish',
    'French',
    'Arabic',
    'Chinese',
  ];

  String get currentLanguage => _currentLanguage;

  void setLanguage(String language) {
    if (supportedLanguages.contains(language) && _currentLanguage != language) {
      _currentLanguage = language;
      notifyListeners();
    }
  }

  String t(String key) {
    return _translations[_currentLanguage]?[key] ?? key;
  }

  static const Map<String, Map<String, String>> _translations = {
    'English': {
      'More': 'More',
      'Features': 'Features',
      'Farm Tasks': 'Farm Tasks',
      'Manage tasks': 'Manage planting, watering & harvest tasks',
      'AI Assistant': 'AI Assistant',
      'Get advice': 'Get smart farming advice',
      'Alerts': 'Alerts',
      'unread alerts': 'unread alerts',
      'Settings': 'Settings',
      'Language': 'Language',
      'About': 'About',
      'Smart Agriculture': 'Smart Agriculture v1.0.0',
      'Logout': 'Logout',
      'Sign out': 'Sign out of your account',
      'Select Language': 'Select Language',
      'Cancel': 'Cancel',
      'Farmer': 'Farmer',
      'Dashboard': 'Dashboard',
      'Crops': 'Crops',
      'Tasks': 'Tasks',
      'Finance': 'Finance',
      'AI': 'AI',
      'Weather Overview': 'Weather Overview',
      'Temperature': 'Temperature',
      'Humidity': 'Humidity',
      'Precipitation': 'Precipitation',
      'Smart Irrigation': 'Smart Irrigation',
      'Soil Moisture': 'Soil Moisture',
      'Pump Status': 'Pump Status',
      'ON': 'ON',
      'OFF': 'OFF',
      'Turn On Pump': 'Turn On Pump',
      'Turn Off Pump': 'Turn Off Pump',
      'Recent Alerts': 'Recent Alerts',
      'My Crops': 'My Crops',
      'Active': 'Active',
      'Harvested': 'Harvested',
      'Add Crop': 'Add Crop',
      'Area': 'Area',
      'Sown': 'Sown',
      'Harvest': 'Harvest',
      'Stage': 'Stage',
      'done': 'done',
      'No tasks yet': 'No tasks yet',
      'Tap + to create one': 'Tap + to create one',
      'Pending': 'Pending',
      'In Progress': 'In Progress',
      'Done': 'Done',
      'Farm Finance': 'Farm Finance',
      'Balance': 'Balance',
      'Income': 'Income',
      'Expenses': 'Expenses',
      'Transactions': 'Transactions',
      'Sales': 'Sales',
      'Add Transaction': 'Add Transaction',
      'Order Fertilizer': 'Order Fertilizer',
      'Farm Assistant': 'Farm Assistant',
      'Ask a question about farming...': 'Ask a question about farming...',
      'No alerts': 'No alerts right now',
    },
    'Hindi': {
      'More': 'और',
      'Features': 'विशेषताएं',
      'Farm Tasks': 'खेत के काम',
      'Manage tasks': 'रोपण, पानी और कटाई कार्यों का प्रबंधन करें',
      'AI Assistant': 'एआई सहायक',
      'Get advice': 'स्मार्ट खेती की सलाह प्राप्त करें',
      'Alerts': 'अलर्ट',
      'unread alerts': 'अपठित अलर्ट',
      'Settings': 'सेटिंग्स',
      'Language': 'भाषा',
      'About': 'के बारे में',
      'Smart Agriculture': 'स्मार्ट कृषि v1.0.0',
      'Logout': 'लॉग आउट',
      'Sign out': 'अपने खाते से साइन आउट करें',
      'Select Language': 'भाषा चुनें',
      'Cancel': 'रद्द करें',
      'Farmer': 'किसान',
      'Dashboard': 'डैशबोर्ड',
      'Crops': 'फसलें',
      'Tasks': 'कार्य',
      'Finance': 'वित्त',
      'AI': 'एआई',
      'Weather Overview': 'मौसम अवलोकन',
      'Temperature': 'तापमान',
      'Humidity': 'नमी',
      'Precipitation': 'वर्षा',
      'Smart Irrigation': 'स्मार्ट सिंचाई',
      'Soil Moisture': 'मिट्टी की नमी',
      'Pump Status': 'पंप की स्थिति',
      'ON': 'चालू',
      'OFF': 'बंद',
      'Turn On Pump': 'पंप चालू करें',
      'Turn Off Pump': 'पंप बंद करें',
      'Recent Alerts': 'हाल के अलर्ट',
      'My Crops': 'मेरी फसलें',
      'Active': 'सक्रिय',
      'Harvested': 'काटी गई',
      'Add Crop': 'फसल जोड़ें',
      'Area': 'क्षेत्र',
      'Sown': 'बोया गया',
      'Harvest': 'कटाई',
      'Stage': 'चरण',
      'done': 'संपन्न',
      'No tasks yet': 'अभी कोई कार्य नहीं',
      'Tap + to create one': 'बनाने के लिए + टैप करें',
      'Pending': 'लंबित',
      'In Progress': 'प्रगति पर',
      'Done': 'संपन्न',
      'Farm Finance': 'खेत का वित्त',
      'Balance': 'शेष',
      'Income': 'आय',
      'Expenses': 'खर्च',
      'Transactions': 'लेन-देन',
      'Sales': 'बिक्री',
      'Add Transaction': 'लेन-देन जोड़ें',
      'Order Fertilizer': 'उर्वरक ऑर्डर करें',
      'Farm Assistant': 'खेत सहायक',
      'Ask a question about farming...': 'खेती के बारे में प्रश्न पूछें...',
      'No alerts': 'अभी कोई अलर्ट नहीं है',
    },
    'Telugu': {
      'More': 'మరిన్ని',
      'Features': 'లక్షణాలు',
      'Farm Tasks': 'పొలం పనులు',
      'Manage tasks': 'పనులను నిర్వహించండి',
      'AI Assistant': 'AI అసిస్టెంట్',
      'Get advice': 'వ్యవసాయ సలహా పొందండి',
      'Alerts': 'హెచ్చరికలు',
      'unread alerts': 'చదవని హెచ్చరికలు',
      'Settings': 'సెట్టింగ్‌లు',
      'Language': 'భాష',
      'About': 'గురించి',
      'Smart Agriculture': 'స్మార్ట్ అగ్రికల్చర్ v1.0.0',
      'Logout': 'లాగ్ అవుట్',
      'Sign out': 'సైన్ అవుట్ చేయండి',
      'Select Language': 'భాషను ఎంచుకోండి',
      'Cancel': 'రద్దు చేయి',
      'Farmer': 'రైతు',
      'Dashboard': 'డాష్‌బోర్డ్',
      'Crops': 'పంటలు',
      'Tasks': 'పనులు',
      'Finance': 'ఆర్థిక',
      'AI': 'AI',
      'Weather Overview': 'వాతావరణం',
      'Temperature': 'ఉష్ణోగ్రత',
      'Humidity': 'తేమ',
      'Precipitation': 'వర్షపాతం',
      'Smart Irrigation': 'స్మార్ట్ ఇరిగేషన్',
      'Soil Moisture': 'నేల తేమ',
      'Pump Status': 'పంపు స్థితి',
      'ON': 'ఆన్',
      'OFF': 'ఆఫ్',
      'Turn On Pump': 'పంపు ఆన్ చేయండి',
      'Turn Off Pump': 'పంపు ఆఫ్ చేయండి',
      'Recent Alerts': 'ఇటీవలి హెచ్చరికలు',
      'My Crops': 'నా పంటలు',
      'Active': 'చురుకుగా',
      'Harvested': 'కోసిన',
      'Add Crop': 'పంటను జోడించండి',
      'Area': 'విస్తీర్ణం',
      'Sown': 'విత్తబడిన',
      'Harvest': 'పంటకోత',
      'Stage': 'దశ',
      'done': 'పూర్తయింది',
      'No tasks yet': 'ఇంకా పనులు లేవు',
      'Tap + to create one': 'సృష్టించడానికి + నొక్కండి',
      'Pending': 'పెండింగ్',
      'In Progress': 'పురోగతిలో ఉంది',
      'Done': 'పూర్తయింది',
      'Farm Finance': 'ఫార్మ్ ఫైనాన్స్',
      'Balance': 'బ్యాలెన్స్',
      'Income': 'ఆదాయం',
      'Expenses': 'ఖర్చులు',
      'Transactions': 'లావాదేవీలు',
      'Sales': 'అమ్మకాలు',
      'Add Transaction': 'లావాదేవీని జోడించండి',
      'Order Fertilizer': 'ఎరువులు ఆర్డర్ చేయండి',
      'Farm Assistant': 'వ్యవసాయ సహాయకుడు',
      'Ask a question about farming...': 'వ్యవసాయం గురించి ఒక ప్రశ్న అడగండి...',
      'No alerts': 'ప్రస్తుతం హెచ్చరికలు లేవు',
    },
    'Tamil': {
      'More': 'மேலும்',
      'Features': 'அம்சங்கள்',
      'Farm Tasks': 'பண்ணை பணிகள்',
      'Manage tasks': 'பணிகளை நிர்வகிக்கவும்',
      'AI Assistant': 'AI உதவியாளர்',
      'Get advice': 'ஆலோசனையைப் பெறுங்கள்',
      'Alerts': 'விழிப்பூட்டல்கள்',
      'unread alerts': 'படிக்காத விழிப்பூட்டல்கள்',
      'Settings': 'அமைப்புகள்',
      'Language': 'மொழி',
      'About': 'பற்றி',
      'Smart Agriculture': 'ஸ்மார்ட் விவசாயம் v1.0.0',
      'Logout': 'வெளியேறு',
      'Sign out': 'வெளியேறவும்',
      'Select Language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'Cancel': 'ரத்துசெய்',
      'Farmer': 'விவசாயி',
      'Dashboard': 'டாஷ்போர்டு',
      'Crops': 'பயிர்கள்',
      'Tasks': 'பணிகள்',
      'Finance': 'நிதி',
      'AI': 'AI',
      'Weather Overview': 'வானிலை மேலோட்டம்',
      'Temperature': 'வெப்பநிலை',
      'Humidity': 'ஈரப்பதம்',
      'Precipitation': 'மழையளவு',
      'Smart Irrigation': 'ஸ்மார்ட் நீர்ப்பாசனம்',
      'Soil Moisture': 'மண் ஈரப்பதம்',
      'Pump Status': 'பம்ப் நிலை',
      'ON': 'ஆன்',
      'OFF': 'ஆஃப்',
      'Turn On Pump': 'பம்பை இயக்கவும்',
      'Turn Off Pump': 'பம்பை அணைக்கவும்',
      'Recent Alerts': 'சமீபத்திய விழிப்பூட்டல்கள்',
      'My Crops': 'என் பயிர்கள்',
      'Active': 'செயலில்',
      'Harvested': 'அறுவடை',
      'Add Crop': 'பயிரைச் சேர்',
      'Area': 'பகுதி',
      'Sown': 'விதைக்கப்பட்டது',
      'Harvest': 'அறுவடை',
      'Stage': 'மேடை',
      'done': 'முடிந்தது',
      'No tasks yet': 'பணிகள் இல்லை',
      'Tap + to create one': 'உருவாக்க + என்பதைத் தட்டவும்',
      'Pending': 'நிலுவையில்',
      'In Progress': 'முன்னேற்றத்தில்',
      'Done': 'முடிந்தது',
      'Farm Finance': 'பண்ணை நிதி',
      'Balance': 'இருப்பு',
      'Income': 'வருமானம்',
      'Expenses': 'செலவுகள்',
      'Transactions': 'பரிவர்த்தனைகள்',
      'Sales': 'விற்பனை',
      'Add Transaction': 'பரிவர்த்தனையைச் சேர்',
      'Order Fertilizer': 'உரத்தை ஆர்டர் செய்யவும்',
      'Farm Assistant': 'பண்ணை உதவியாளர்',
      'Ask a question about farming...':
          'விவசாயம் பற்றி ஒரு கேள்வி கேளுங்கள்...',
      'No alerts': 'தற்போது விழிப்பூட்டல்கள் இல்லை',
    },
    'Marathi': {
      'More': 'अधिक',
      'Features': 'वैशिष्ट्ये',
      'Farm Tasks': 'शेतीची कामे',
      'Manage tasks': 'कामे व्यवस्थापित करा',
      'AI Assistant': 'एआय सहाय्यक',
      'Get advice': 'सल्ला मिळवा',
      'Alerts': 'सूचना',
      'unread alerts': 'न वाचलेले अलर्ट',
      'Settings': 'सेटिंग्ज',
      'Language': 'भाषा',
      'About': 'बद्दल',
      'Smart Agriculture': 'स्मार्ट कृषी v1.0.0',
      'Logout': 'लॉग आउट',
      'Sign out': 'साइन आउट करा',
      'Select Language': 'भाषा निवडा',
      'Cancel': 'रद्द करा',
      'Farmer': 'शेतकरी',
      'Dashboard': 'डॅशबोर्ड',
      'Crops': 'पिके',
      'Tasks': 'कामे',
      'Finance': 'वित्त',
      'AI': 'एआय',
      'Weather Overview': 'हवामान विहंगावलोकन',
      'Temperature': 'तापमान',
      'Humidity': 'आर्द्रता',
      'Precipitation': 'पाऊस',
      'Smart Irrigation': 'स्मार्ट सिंचन',
      'Soil Moisture': 'मातीची आर्द्रता',
      'Pump Status': 'पंप स्थिती',
      'ON': 'चालू',
      'OFF': 'बंद',
      'Turn On Pump': 'पंप चालू करा',
      'Turn Off Pump': 'पंप बंद करा',
      'Recent Alerts': 'अलीकडील सूचना',
      'My Crops': 'माझी पिके',
      'Active': 'सक्रिय',
      'Harvested': 'कापणी',
      'Add Crop': 'पीक जोडा',
      'Area': 'क्षेत्र',
      'Sown': 'पेरणी',
      'Harvest': 'कापणी',
      'Stage': 'टप्पा',
      'done': 'झाले',
      'No tasks yet': 'अद्याप कोणतीही कामे नाहीत',
      'Tap + to create one': 'तयार करण्यासाठी + टॅप करा',
      'Pending': 'प्रलंबित',
      'In Progress': 'प्रगतीपथावर',
      'Done': 'झाले',
      'Farm Finance': 'शेती वित्त',
      'Balance': 'शिल्लक',
      'Income': 'उत्पन्न',
      'Expenses': 'खर्च',
      'Transactions': 'व्यवहार',
      'Sales': 'विक्री',
      'Add Transaction': 'व्यवहार जोडा',
      'Order Fertilizer': 'खत ऑर्डर करा',
      'Farm Assistant': 'शेती सहाय्यक',
      'Ask a question about farming...': 'शेतीबद्दल प्रश्न विचारा...',
      'No alerts': 'सध्या कोणतीही सूचना नाही',
    },
    'Spanish': {
      'More': 'Más',
      'Features': 'Características',
      'Farm Tasks': 'Tareas Agrícolas',
      'Manage tasks': 'Gestionar tareas',
      'AI Assistant': 'Asistente IA',
      'Get advice': 'Obtener consejos',
      'Alerts': 'Alertas',
      'unread alerts': 'alertas no leídas',
      'Settings': 'Ajustes',
      'Language': 'Idioma',
      'About': 'Acerca de',
      'Smart Agriculture': 'Agricultura Inteligente v1.0.0',
      'Logout': 'Cerrar sesión',
      'Sign out': 'Cierra sesión',
      'Select Language': 'Seleccionar idioma',
      'Cancel': 'Cancelar',
      'Farmer': 'Agricultor',
      'Dashboard': 'Tablero',
      'Crops': 'Cultivos',
      'Tasks': 'Tareas',
      'Finance': 'Finanzas',
      'AI': 'IA',
      'Weather Overview': 'Resumen del Clima',
      'Temperature': 'Temperatura',
      'Humidity': 'Humedad',
      'Precipitation': 'Precipitación',
      'Smart Irrigation': 'Riego Inteligente',
      'Soil Moisture': 'Humedad del Suelo',
      'Pump Status': 'Estado de la Bomba',
      'ON': 'ENCENDIDO',
      'OFF': 'APAGADO',
      'Turn On Pump': 'Encender Bomba',
      'Turn Off Pump': 'Apagar Bomba',
      'Recent Alerts': 'Alertas Recientes',
      'My Crops': 'Mis Cultivos',
      'Active': 'Activo',
      'Harvested': 'Cosechado',
      'Add Crop': 'Agregar Cultivo',
      'Area': 'Área',
      'Sown': 'Sembrado',
      'Harvest': 'Cosecha',
      'Stage': 'Etapa',
      'done': 'hecho',
      'No tasks yet': 'Aún no hay tareas',
      'Tap + to create one': 'Toca + para crear',
      'Pending': 'Pendiente',
      'In Progress': 'En Curso',
      'Done': 'Hecho',
      'Farm Finance': 'Finanzas Agrícolas',
      'Balance': 'Saldo',
      'Income': 'Ingresos',
      'Expenses': 'Gastos',
      'Transactions': 'Transacciones',
      'Sales': 'Ventas',
      'Add Transaction': 'Agregar Transacción',
      'Order Fertilizer': 'Pedir Fertilizante',
      'Farm Assistant': 'Asistente Agrícola',
      'Ask a question about farming...':
          'Haz una pregunta sobre agricultura...',
      'No alerts': 'No hay alertas en este momento',
    },
    'French': {
      'More': 'Plus',
      'Features': 'Caractéristiques',
      'Farm Tasks': 'Tâches Agricoles',
      'Manage tasks': 'Gérer les tâches',
      'AI Assistant': 'Assistant IA',
      'Get advice': 'Obtenir des conseils',
      'Alerts': 'Alertes',
      'unread alerts': 'alertes non lues',
      'Settings': 'Paramètres',
      'Language': 'Langue',
      'About': 'À propos',
      'Smart Agriculture': 'Agriculture Intelligente v1.0.0',
      'Logout': 'Se déconnecter',
      'Sign out': 'Déconnectez-vous',
      'Select Language': 'Choisir la langue',
      'Cancel': 'Annuler',
      'Farmer': 'Agriculteur',
      'Dashboard': 'Tableau de bord',
      'Crops': 'Cultures',
      'Tasks': 'Tâches',
      'Finance': 'Finances',
      'AI': 'IA',
      'Weather Overview': 'Météo',
      'Temperature': 'Température',
      'Humidity': 'Humidité',
      'Precipitation': 'Précipitation',
      'Smart Irrigation': 'Irrigation Intelligente',
      'Soil Moisture': 'Humidité du sol',
      'Pump Status': 'Statut de la Pompe',
      'ON': 'MARCHE',
      'OFF': 'ARRÊT',
      'Turn On Pump': 'Allumer Pompe',
      'Turn Off Pump': 'Éteindre Pompe',
      'Recent Alerts': 'Alertes Récentes',
      'My Crops': 'Mes Cultures',
      'Active': 'Actif',
      'Harvested': 'Récolté',
      'Add Crop': 'Ajouter Culture',
      'Area': 'Superficie',
      'Sown': 'Semé',
      'Harvest': 'Récolte',
      'Stage': 'Stade',
      'done': 'fait',
      'No tasks yet': 'Aucune tâche',
      'Tap + to create one': 'Appuyez sur + pour créer',
      'Pending': 'En attente',
      'In Progress': 'En cours',
      'Done': 'Terminé',
      'Farm Finance': 'Finances Agricoles',
      'Balance': 'Solde',
      'Income': 'Revenu',
      'Expenses': 'Dépenses',
      'Transactions': 'Transactions',
      'Sales': 'Ventes',
      'Add Transaction': 'Ajouter Transaction',
      'Order Fertilizer': 'Commander de l\'engrais',
      'Farm Assistant': 'Assistant Agricole',
      'Ask a question about farming...':
          'Posez une question sur l\'agriculture...',
      'No alerts': 'Aucune alerte pour le moment',
    },
    'Arabic': {
      'More': 'المزيد',
      'Features': 'الميزات',
      'Farm Tasks': 'مهام المزرعة',
      'Manage tasks': 'إدارة المهام',
      'AI Assistant': 'مساعد ذكي',
      'Get advice': 'احصل على نصيحة',
      'Alerts': 'تنبيهات',
      'unread alerts': 'تنبيهات غير مقروءة',
      'Settings': 'إعدادات',
      'Language': 'لغة',
      'About': 'عن',
      'Smart Agriculture': 'الزراعة الذكية v1.0.0',
      'Logout': 'تسجيل خروج',
      'Sign out': 'تسجيل الخروج',
      'Select Language': 'اختار اللغة',
      'Cancel': 'إلغاء',
      'Farmer': 'مزارع',
      'Dashboard': 'لوحة القيادة',
      'Crops': 'المحاصيل',
      'Tasks': 'المهام',
      'Finance': 'المالية',
      'AI': 'الذكاء الاصطناعي',
      'Weather Overview': 'نظرة عامة على الطقس',
      'Temperature': 'درجة الحرارة',
      'Humidity': 'رطوبة',
      'Precipitation': 'هطول الأمطار',
      'Smart Irrigation': 'الري الذكي',
      'Soil Moisture': 'رطوبة التربة',
      'Pump Status': 'حالة المضخة',
      'ON': 'تشغيل',
      'OFF': 'إيقاف',
      'Turn On Pump': 'تشغيل المضخة',
      'Turn Off Pump': 'إيقاف المضخة',
      'Recent Alerts': 'تنبيهات حديثة',
      'My Crops': 'محاصيلي',
      'Active': 'نشط',
      'Harvested': 'تم الحصاد',
      'Add Crop': 'إضافة محصول',
      'Area': 'مساحة',
      'Sown': 'مزروع',
      'Harvest': 'حصاد',
      'Stage': 'مرحلة',
      'done': 'تم',
      'No tasks yet': 'لا توجد مهام',
      'Tap + to create one': 'اضغط + لإنشاء واحدة',
      'Pending': 'قيد الانتظار',
      'In Progress': 'قيد التقدم',
      'Done': 'تم',
      'Farm Finance': 'تمويل المزرعة',
      'Balance': 'رصيد',
      'Income': 'دخل',
      'Expenses': 'نفقات',
      'Transactions': 'المعاملات',
      'Sales': 'المبيعات',
      'Add Transaction': 'إضافة معاملة',
      'Order Fertilizer': 'اطلب سماد',
      'Farm Assistant': 'مساعد المزرعة',
      'Ask a question about farming...': 'اطرح سؤالا عن الزراعة...',
      'No alerts': 'لا توجد تنبيهات في الوقت الحالي',
    },
    'Chinese': {
      'More': '更多',
      'Features': '功能',
      'Farm Tasks': '农场任务',
      'Manage tasks': '管理任务',
      'AI Assistant': '人工智能助手',
      'Get advice': '获取建议',
      'Alerts': '警报',
      'unread alerts': '未读警报',
      'Settings': '设置',
      'Language': '语言',
      'About': '关于',
      'Smart Agriculture': '智能农业 v1.0.0',
      'Logout': '注销',
      'Sign out': '退出',
      'Select Language': '选择语言',
      'Cancel': '取消',
      'Farmer': '农民',
      'Dashboard': '仪表板',
      'Crops': '农作物',
      'Tasks': '任务',
      'Finance': '财务',
      'AI': '人工智能',
      'Weather Overview': '天气概况',
      'Temperature': '温度',
      'Humidity': '湿度',
      'Precipitation': '降水',
      'Smart Irrigation': '智能灌溉',
      'Soil Moisture': '土壤湿度',
      'Pump Status': '水泵状态',
      'ON': '开',
      'OFF': '关',
      'Turn On Pump': '打开水泵',
      'Turn Off Pump': '关闭水泵',
      'Recent Alerts': '最近的警报',
      'My Crops': '我的农作物',
      'Active': '活跃',
      'Harvested': '已收割',
      'Add Crop': '添加农作物',
      'Area': '面积',
      'Sown': '播种',
      'Harvest': '收获',
      'Stage': '阶段',
      'done': '完成',
      'No tasks yet': '暂无任务',
      'Tap + to create one': '点击 + 创建',
      'Pending': '待办',
      'In Progress': '进行中',
      'Done': '完成',
      'Farm Finance': '农场财务',
      'Balance': '余额',
      'Income': '收入',
      'Expenses': '支出',
      'Transactions': '交易',
      'Sales': '销售额',
      'Add Transaction': '添加交易',
      'Order Fertilizer': '订购肥料',
      'Farm Assistant': '农场助手',
      'Ask a question about farming...': '问一个关于农业的问题...',
      'No alerts': '目前没有警报',
    },
  };
}
